name: Deploy Node.js App to Minikube

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube

    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Check Cluster
      run: kubectl get nodes

    - name: Build Docker Image
      run: |
        eval $(minikube -p minikube docker-env)
        docker build -t lakshmichalla84/node-app:latest .
        docker images

    - name: Deploy App to Minikube
      run: |
        kubectl apply -f k8s-node-app.yaml
        kubectl rollout status deployment/nodejs-app

    - name: Get Service URL
      run: |
        minikube service nodejs-app --url
